server:
  port: 8081
spring:
  main:
    allow-bean-definition-overriding: true
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuerUri: http://localhost:8080/auth/realms/master
        registration:
          keycloak:
            authorization-grant-type: client_credentials
            client-id: payment-app
            client-secret: b11bcb8b-9521-4da9-bac5-a8bc90589409
            token-uri: http://localhost:8080/auth/realms/master/protocol/openid-connect/token

